// Exercice 2: GÃ©rer les erreurs avec try...catch

try {
    nonExistentFunction();
  } catch (error) {
    console.error(error);
  }
  